export default  [
  {
    title: "The Hefalump's Tale",
    page: '32',
    line: '1',
    author: 'Joni E. Driskill',
    genre: 'Sci-fi',
    type: 'Motivational',
    content: 'The grass is greener on the other side.',
    claps: 23,
    id: 1,
    comments: [
      {
        id: 0,
        content: 'Comment content',
        author: 'author',
        claps: 2,
      },
      {
        id: 1,
        content: 'Comment content',
        author: 'author',
        claps: 4,
      },
      {
        id: 2,
        content: 'Comment content',
        author: 'author',
        claps: 12,
      },
    ],
  },
  {
    title: "Righteous Living",
    page: '498',
    line: '51',
    author: 'Daniel K. Driskill',
    genre: 'Non-fiction',
    type: 'Inspirational',
    content: "Don't give monkeys machine guns.",
    claps: 8,
    id: 2,
    comments: [
      {
        id: 0,
        content: 'Comment content',
        author: 'author',
        claps: 2,
      },
      {
        id: 1,
        content: 'Comment content',
        author: 'author',
        claps: 4,
      },
      {
        id: 2,
        content: 'Comment content',
        author: 'author',
        claps: 12,
      },
    ],
  },
  {
    title: "How to Train Your Dragon",
    page: '868',
    line: '2',
    author: 'James C. Driskill',
    genre: 'Fantasy',
    type: 'Prose',
    content: 'Long was the night...',
    claps: 7,
    id: 3,
    comments: [
      {
        id: 0,
        content: 'Comment content',
        author: 'author',
        claps: 2,
      },
      {
        id: 1,
        content: 'Comment content',
        author: 'author',
        claps: 4,
      },
      {
        id: 2,
        content: 'Comment content',
        author: 'author',
        claps: 12,
      },
    ],
  },
  {
    title: "The Hefalump's Tale",
    page: '32',
    line: '1',
    author: 'Joni E. Driskill',
    genre: 'Sci-fi',
    type: 'Motivational',
    content: 'The grass is greener on the other side, unless, in actuality and reality, it is not.',
    claps: 23,
    id: 4,
    comments: [
      {
        id: 0,
        content: 'Comment content',
        author: 'author',
        claps: 2,
      },
      {
        id: 1,
        content: 'Comment content',
        author: 'author',
        claps: 4,
      },
      {
        id: 2,
        content: 'Comment content',
        author: 'author',
        claps: 12,
      },
    ],
  },
  {
    title: "Righteous Living",
    page: '498',
    line: '51',
    author: 'Daniel K. Driskill',
    genre: 'Non-fiction',
    type: 'Inspirational',
    content: "Don't give monkeys machine guns.",
    claps: 8,
    id: 5,
    comments: [
      {
        id: 0,
        content: 'Comment content',
        author: 'author',
        claps: 2,
      },
      {
        id: 1,
        content: 'Comment content',
        author: 'author',
        claps: 4,
      },
      {
        id: 2,
        content: 'Comment content',
        author: 'author',
        claps: 12,
      },
    ],
  },
  {
    title: "How to Train Your Dragon",
    page: '868',
    line: '2',
    author: 'James C. Driskill',
    genre: 'Fantasy',
    type: 'Poetry',
    content: 'Long was the night...',
    claps: 7,
    id: 6,
    comments: [
      {
        id: 0,
        content: 'Comment content',
        author: 'author',
        claps: 2,
      },
      {
        id: 1,
        content: 'Comment content',
        author: 'author',
        claps: 4,
      },
      {
        id: 2,
        content: 'Comment content',
        author: 'author',
        claps: 12,
      },
    ],
  },
];
