export default  [
  {
    title: "The Hefalump's Tale",
    page: '32',
    line: '1',
    author: 'Joni E. Driskill',
    genre: 'Sci-fi',
    type: 'Motivational',
    content: 'The grass is greener on the other side.',
    claps: 23,
    id: 1,
    user: {
      userId: 0,
      username: 'yoloswaggins',
    },
    comments: [
      {
        commentId: 0,
        quoteId: 0,
        content: 'Comment content',
        userId: 'userId',
        claps: 2,
        date: 0,
      },
      {
        commentId: 1,
        quoteId: 1,
        content: 'Comment content',
        userId: 'userId',
        claps: 4,
        date: 1,
      },
      {
        commentId: 2,
        quoteId: 2,
        content: 'Comment content',
        userId: 'userId',
        claps: 12,
        date: 2,
      },
    ],
  },
  {
    title: "Righteous Living",
    page: '498',
    line: '51',
    author: 'Daniel K. Driskill',
    genre: 'Non-fiction',
    type: 'Inspirational',
    content: "Don't give monkeys machine guns.",
    claps: 8,
    id: 2,
    user: {
      userId: 1,
      username: 'bogochaggins',
    },
    comments: [
      {
        commentId: 0,
        quoteId: 0,
        content: 'Comment content',
        userId: 'userId',
        claps: 2,
        date: 0,
      },
      {
        commentId: 1,
        quoteId: 1,
        content: 'Comment content',
        userId: 'userId',
        claps: 4,
        date: 1,
      },
      {
        commentId: 2,
        quoteId: 2,
        content: 'Comment content',
        userId: 'userId',
        claps: 12,
        date: 2,
      },
    ],
  },
  {
    title: "How to Train Your Dragon",
    page: '',
    line: '',
    author: 'James C. Driskill',
    genre: 'Fantasy',
    type: 'Prose',
    content: 'Long was the night...',
    claps: 7,
    id: 3,
    user: {
      userId: 2,
      username: 'pippinandmerry',
    },
    comments: [
      {
        commentId: 0,
        quoteId: 0,
        content: 'Comment content',
        userId: 'userId',
        claps: 2,
        date: 0,
      },
      {
        commentId: 1,
        quoteId: 1,
        content: 'Comment content',
        userId: 'userId',
        claps: 4,
        date: 1,
      },
      {
        commentId: 2,
        quoteId: 2,
        content: 'Comment content',
        userId: 'userId',
        claps: 12,
        date: 2,
      },
    ],
  },
  {
    title: "The Hefalump's Tale",
    page: '32',
    line: '1',
    author: 'Joni E. Driskill',
    genre: 'Sci-fi',
    type: 'Motivational',
    content: 'The grass is greener on the other side, unless, in actuality and reality, it is not. I guess in that case, you can just give up on anything nice in life.',
    claps: 23,
    id: 4,
    user: {
      userId: 3,
      username: 'aragorn',
    },
    comments: [
      {
        commentId: 0,
        quoteId: 0,
        content: 'Comment content',
        userId: 'userId',
        claps: 2,
        date: 2,
      },
      {
        commentId: 1,
        quoteId: 1,
        content: 'Comment content',
        userId: 'userId',
        claps: 4,
        date: 1,
      },
      {
        commentId: 2,
        quoteId: 2,
        content: 'Comment content',
        userId: 'userId',
        claps: 12,
        date: 0,
      },
    ],
  },
  {
    title: "Righteous Living",
    page: '498',
    line: '',
    author: 'Daniel K. Driskill',
    genre: 'Non-fiction',
    type: 'Inspirational',
    content: "Don't give monkeys machine guns.",
    claps: 8,
    id: 5,
    user: {
      userId: 4,
      username: 'elrondthewise',
    },
    comments: [
      {
        commentId: 0,
        quoteId: 0,
        content: 'Comment content',
        userId: 'userId',
        claps: 2,
        date: 0,
      },
      {
        commentId: 1,
        quoteId: 1,
        content: 'Comment content',
        userId: 'userId',
        claps: 4,
        date: 1,
      },
      {
        commentId: 2,
        quoteId: 2,
        content: 'Comment content',
        userId: 'userId',
        claps: 12,
        date: 2,
      },
    ],
  },
  {
    title: "How to Train Your Dragon",
    page: '868',
    line: '2',
    author: 'James C. Driskill',
    genre: 'Fantasy',
    type: 'Poetry',
    content: 'Long was the night...',
    claps: 7,
    id: 6,
    user: {
      userId: 5,
      username: 'balrog',
    },
    comments: [
      {
        commentId: 0,
        quoteId: 0,
        content: 'Comment content',
        userId: 'userId',
        claps: 2,
        date: 0,
      },
      {
        commentId: 1,
        quoteId: 1,
        content: 'Comment content',
        userId: 'userId',
        claps: 4,
        date: 1,
      },
      {
        commentId: 2,
        quoteId: 2,
        content: 'Comment content',
        userId: 'userId',
        claps: 12,
        date: 2,
      },
    ],
  },
];
