// Move to backend one day? IDK

export const genres = [
  'fiction',
  'non-fiction',
  'biography',
  'autobiography',
  'essay',
  'narrative',
  'poetry',
  'drama',
  'suspense/thriller',
  'mystery',
  'romance',
  'adventure',
  'action',
  'fantasy',
  'sci-fi',
  'horror',
  'western',
  'comedy',
  'other',
  'history',
  'crime',
  'self-help',
  'speech',
  'textbook',
  'business',
  'how-to',
  'literarature',
  'philosophy',
  'politics',
  'science',
  'religion',
  'speculative',
  'tragedy',
  'diary/journal',
].sort();

export const types = [
  'motivational',
  'inspirational',
  'instructional',
  'prose',
  'poetry',
  'other',
  'entertaining',
  'fascinating',
].sort();
